### ISSUE TITLE
Key Vault authentication & Azure deployment

### ISSUE THREAD

**Issue by nauduberteau** [RuiRomano/pbimonitor#14]
Hi,

I tried to deploy the project on our Azure subscription from de .zip file, but the environnement variables are not created.
Does I have to include the config.json in the compress archive ?

Also, I didn't saw where the Key Vault is used in your scripts. Does I have to change anything to use this authentication method ?

Thanks for your sharing by the way, gold sources for Power BI administration. :)

Regards

**Comment by Oddjobe** [comment]
![image](https://user-images.githubusercontent.com/15087494/164720152-b48e84cc-10e3-4984-aa8e-891b1f557189.png)

I configured the solution with key-vault and it works fine.
You need give the azure functions identity access to your key-vault first
