### ISSUE TITLE
No data for Tables/Columns

### ISSUE THREAD

**Issue by vjalil** [RuiRomano/pbimonitor#16]
Hi, I'm using your Azure Function and I noticed that the default value for "$getInfoDetails" in "Fetch - Catalog.ps1" is:

$getInfoDetails = "lineage=true&datasourceDetails=true&getArtifactUsers=true&datasetSchema=false&datasetExpressions=false"

"datasetSchema=false" and "datasetExpressions=false" is excluding tables/columns details right?

I don't have the PBIMONITOR_CatalogGetInfoParameters Application Setting in the Azure Function Configuration, would that be the reason? If so, what value should I use? "lineage=true&datasourceDetails=true&getArtifactUsers=true&datasetSchema=TRUE&datasetExpressions=TRUE"?

Thanks for your solution btw, It's been really helpful!!!
Vanessa

**Comment by RuiRomano** [comment]
You are correct, by default I dont collect schema & expressions.
But you can override that setting using the setting ' PBIMONITOR_CatalogGetInfoParameters'
