### ISSUE TITLE
pbilog

### ISSUE THREAD

**Issue by dbhupla** [RuiRomano/pbimonitor#17]
Hi,

Please could you advise where I can find the pbilog value.. is this something that needs creating?

![image](https://user-images.githubusercontent.com/102581183/177303259-f26323d5-fdeb-411b-803a-4343d0286f07.png)

Also do we use the appID and tenantID from the App Secret (App registration)

**Comment by RuiRomano** [comment]
its typo, the pbilog its the appsecret
