### ISSUE TITLE
ActivityEvents are returning blanks

### ISSUE THREAD

**Issue by cvillegashak** [RuiRomano/pbimonitor#2]
When executing all of the steps provided everything appears to work except for the ActivityEvents portion. The set of json files for Activities are fairly large so I can tell that it's finding data, but the outputs appear to be empty when polling details with repeating rows like this over and over again:

[{"Id":[],"RecordType":[],"CreationTime":[],"Operation":[],"OrganizationId":[],"UserType":[],"UserKey":[],"Workload":[],"UserId":[],"ClientIP":[],"UserAgent":[],"Activity":[],"ItemName":[],"WorkSpaceName":[],"CapacityId":[],"CapacityName":[],"WorkspaceId":[],"ObjectId":[],"DataflowId":[],"DataflowName":[]

The document doesn't list any prerequesites for this portion of the process as far as permissions, but I know that the activity events api requires this:

Global admins and Power BI service admins have access.

Is there anything that could be missing possibly?

**Comment by RuiRomano** [comment]
Can you please verify if its still happening with the last version?
