### ISSUE TITLE
Limit Audits to a subscription

### ISSUE THREAD

**Issue by azure-walker** [RuiRomano/pbimonitor#23]
I am looking through the code to see if there is a way to limit the PBI Monitor to a specific subscription instead of pulling information from across the Tenant.

**Comment by RuiRomano** [comment]
You mean capacity? Unfortunately, the Activity Events API only allows to filter by ‘Activity’ or 'UserId' 
https://learn.microsoft.com/en-us/rest/api/power-bi/admin/get-activity-events
