### ISSUE TITLE
FetchGraph.ps1

### ISSUE THREAD

**Issue by byteboy78** [RuiRomano/pbimonitor#38]
Hi,

This uses access token.  Is there another way to login interactively and extract this data?

Thanks.

**Comment by JamesDBartlett3** [comment]
@byteboy78, I've attached a customized version of `Fetch - Graph.ps1` which automatically:
- installs the `Az.Accounts` module if it is not already installed
- imports the `Fetch - Utils.psm1` module from the same folder where the script is stored
- populates necessary `$config` properties if the `$config` parameter is not specified
- authenticates as the current user (`Get-AzAccessToken`) if Service Principal credentials are not found in `$config` parameter

Download here: [FetchGraph.zip](https://github.com/RuiRomano/pbimonitor/files/14829038/FetchGraph.zip)

_Note: The `Fetch - Utils.psm1` module must remain in the same folder with the script, or you'll have to modify the path on line 14 of the script._

I just tested the attached script by extracting the zip file into a new folder and executing it from there with no parameters. It successfully authenticated with my current user account, called the Graph APIs, and dumped the expected data into a new folder called `graph`. I'm marking this issue as closed for now, but if it doesn't work for you, please tag me in a new comment, and I'll re-open the issue.
