### ISSUE TITLE
Deleted reports still showing

### ISSUE THREAD

**Issue by JaimyPolhuis** [RuiRomano/pbimonitor#47]
First of all, really appreciate this solution. Overall it works well, but as soon as I delete a report, it will still show in the Power BI monitor report 2 weeks after (the refresh was done and all other things seem to show well). Does it take more time to let these reports disappear or might there be another reason?

**Comment by FrankPreusker** [comment]
Any kind of deletion (workspaces, reports, datasets, even tables, measures, etc) will only be visible with your next full refresh, but not with any of the incremental ones.

**Comment by JaimyPolhuis** [comment]
Okay, thanks for your reply @FrankPreusker! Do you maybe know if this full refresh can be made more frequent?

**Comment by WillCisler** [comment]
If you have deployed to Azure then there is a configuration variable for the days till full refresh. For a local run I would check the code for the configuration JSON file

**Comment by WillCisler** [comment]
Yes the local run uses a hard coded value in the JSON.

    "FullScanAfterDays": "30",

**Comment by FrankPreusker** [comment]
Yes, you can easily modify that in the config.json file. Mainly for the reason to catch deletions earlier we have set this to only seven days.
![image](https://github.com/RuiRomano/pbimonitor/assets/74618614/98211d0f-1b5f-4983-9ac4-bb62951c4b70)
